spring:
  application:
    name: healflow-platform
  datasource:
    url: jdbc:h2:mem:healflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

healflow:
  enabled: true
  exception-listener-enabled: true
  high-severity-token: panic
  sandbox:
    image: "ubuntu:latest"
  git:
    token: ${GIT_TOKEN:}
